exports.port = process.env.PORT || 3000;
exports.enable_logging = true;
exports.fetch_regex = /^\/(.*)$/; // リクエストを解析するときに探すURL。
exports.proxy_request_timeout_ms = 10000; // タイムアウトする前に、プロキシサーバーが応答するのを待つ時間。
exports.max_request_length = 10737418240; // 要求または応答に許可される最大文字長。
exports.enable_rate_limiting = true;
exports.max_requests_per_second = 10; // 特定のIPから許可される1秒あたりの最大リクエスト数。
exports.blacklist_hostname_regex = /^(10\.|192\.|127\.|localhost$)/i; // 内部IPアドレスとホストへのアクセスを制限するのに適しています。
exports.cluster_process_count = Number(process.env.CLUSTER_PROCESS_COUNT) || require("os").cpus().length;
